// Package httpport provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package httpport

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Error Error description
type Error struct {
	Message string `json:"message"`
}

// Query Body of the GET request to the endpoint
type Query struct {
	// Body User message
	Body string `json:"body"`

	// Uuid User's unique identifier
	Uuid openapi_types.UUID `json:"uuid"`
}

// Reply Body of the GET response from the endpoint
type Reply struct {
	// Body Bot reply
	Body string `json:"body"`

	// Uuid User's unique identifier
	Uuid openapi_types.UUID `json:"uuid"`
}

// GetReplyJSONRequestBody defines body for GetReply for application/json ContentType.
type GetReplyJSONRequestBody = Query
